std_msgs/Header header

float64[] q
float64[] qdot
float64[] dq
float64[] dqdot
float64[] torque
float64 Kp_T
float64 Kp_R
float64 emgsigg

float64[] Kp_emgg
float64[] Kd_emgg
float64[] Mx_diag

geometry_msgs/Pose[] x
geometry_msgs/Pose[] dx
geometry_msgs/Pose[] dx2

float64[] InverseConditionNum
float64 MM
float64 DAMM
float64 TODAMM
float64[] SingleMM
float64[] lambda1
float64[] lambda2
float64[] ftsensor
float64 KE
float64[] torque_ext
float64[] xdot
float64[] dxdot
float64[] dxddot
geometry_msgs/Pose[] ex
